apiVersion: v1
kind: Namespace
metadata:
  name: pingspeed
---
apiVersion: v1
kind: Service
metadata:
  name: pingspeed
  namespace: pingspeed
  labels:
    app: pingspeed
spec:
  type: NodePort
  metadata:
    labels:
      app: pingspeed
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 8081
      targetPort: 8081
  selector:
    app: pingspeed
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pingspeed
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - pingspeed
  selector:
    matchLabels:
      app: pingspeed
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingspeed
  namespace: pingspeed
spec:
  selector:
    matchLabels:
      app: pingspeed
  replicas: 3
  template:
    metadata:
      labels:
        app: pingspeed
    spec:
      containers:
        - name: pingspeed
          image: registry.brotherlogic-backend.com/brotherlogic/pingspeed:0.982.0 # {"$imagepolicy": "flux-system:pingspeed"}
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred
